name: Deploy to GitHub Pages

on:
  push:
    branches: [main]        # mainブランチにpushされたら実行

permissions:
  contents: write           # gh-pagesブランチへのpushに必要

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ソース取得
      - name: Checkout
        uses: actions/checkout@v4

      # Nodeセットアップ
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 依存インストール
      - name: Install dependencies
        run: npm ci

      # Viteビルド
      - name: Build
        run: |
          npm run build
          cp dist/index.html dist/404.html
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      # gh-pagesブランチへデプロイ
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages